background_opacity 0.65

background #171E3B
foreground #D8E8FF

cursor #5FFFE4
cursor_text_color #171E3B

selection_background #26718F
selection_foreground #FFFFFF

color0  #171E3B
color1  #FF6B8A
color2  #5FFFE4
color3  #FFE66D
color4  #5C8DFF
color5  #B58CFF
color6  #4DEEEA
color7  #D8E8FF

color8  #53617A
color9  #FF7895
color10 #78FFE8
color11 #FFF08A
color12 #79A5FF
color13 #C49DFF
color14 #70F7F3
color15 #FFFFFF

confirm_os_window_close 0
